version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "filmodb"
      POSTGRES_USER: "filmodbuser"
      POSTGRES_PASSWORD: "filmodbpass"
    volumes:
      - filmodata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - filmonet
    restart: unless-stopped

  filmosearch:
    image: filmosearch:latest
    volumes:
      - logs:/Logs
    ports:
      - 80:80
      - 443:443
    networks:
      - filmonet
    depends_on:
      postgres:
        condition: "service_started"
    restart: unless-stopped


volumes:
  filmodata: 
      driver: local
      driver_opts:
         o: bind
         type: none
         device: ${GITHUB_WORKSPACE}/postgresql/data
  logs:
      driver: local
      driver_opts:
         o: bind
         type: none
         device: ${GITHUB_WORKSPACE}/Logs

networks:
  filmonet:
    driver: bridge
