version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "filmodb"
      POSTGRES_USER: "filmodbuser"
      POSTGRES_PASSWORD: "filmodbpass"
    volumes:
      - filmodata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  filmodata: 
      driver: local
      driver_opts:
         o: bind
         type: none
         device: ./postgresql/data