version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "filmodb"
      POSTGRES_USER: "filmodbuser"
      POSTGRES_PASSWORD: "filmodbpass"
    volumes:
      - filmodb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"