name: Testing at merge into main
on:
  merge_group:
    branches:
      - master

jobs:
  tests:
    name: Unit Testing
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0
          
      - name: Running tests
        run: dotnet test
